branches:
  only:
    - master
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.5
    - python: 3.4
cache: pip
addons:
  postgresql: '9.6'
install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install
before_script:
  - psql -U postgres -c "create database karaoke;"
script: pipenv run python -m unittest discover -s tests
